### PR TITLE
add PMIX and MPI libs to MOC library

### PR DESCRIPTION
**Pull request by naughtont3**

### CODE REVIEW

**Comment by gvallee** [comment]
Will it not make more sense to add implicitly these flags to the FLAGS in configure.ac? It is already the place where we set the path for the headers and the libs. Does it make sense?

**Comment by naughtont3** [comment]
Good point, I'll take a look and see.

**Comment by gvallee** [comment]
I already have a patch, let me push it.

**Comment by naughtont3** [comment]
Closing this in favor of #4.

**Pull request closed without merging**
